---
- name: php composer - get
  get_url: url=https://getcomposer.org/installer dest=/home/vagrant/composer-setup.php

- name: php composer - install
  shell: php /home/vagrant/composer-setup.php --install-dir=/usr/local/bin creates=/usr/local/bin/composer

- name: php composer - rename to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

#- name: php composer - delete setup file
#  file: path=/home/vagrant/composer-setup.php state=absent
