---
- name: install system packages
  apt: name={{ item }} state=latest
  with_items: '{{ system_packages }}'

- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- include: apache2.yml
- include: mailhog.yml
- include: php.yml
- include: composer.yml
- include: mysql.yml
- include: phpmyadmin.yml
- include: nodejs.yml
- include: yarn.yml
- include: mc.yml
