---
- name: install system packages
  apt:
    name: '{{ system_packages }}'
    state: latest

- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- include: apache2.yml
- include: mailhog.yml
- include: php.yml
- include: composer.yml
- include: mysql.yml
- include: phpmyadmin.yml
- include: nodejs.yml
- include: yarn.yml
- include: mc.yml
