---
- name: nodejs - get
  get_url: url=https://deb.nodesource.com/setup_8.x dest=/home/vagrant/nodejs_setup.sh mode=u+x

- name: nodejs - run script
  shell: /home/vagrant/nodejs_setup.sh removes /home/vagrant/nodejs_setup.sh

- name: nodejs - install
  apt: name=nodejs state=latest

- name: nodejs - install packages globally
  npm: name={{ item }} global=yes state=latest
  with_items: '{{ nodejs_modules }}'
#  changed_when: False
