---
- name: php5 - install packages
  apt: name={{ item }} state=latest
  with_items: '{{ php56_packages }}'

- name: php5 - ini settings
  ini_file: dest=/etc/php5/fpm/php.ini section={{ item.value.chapter }} option={{ item.key }} value={{ item.value.val }}
  with_dict: '{{ php56_ini }}'
  notify:
  - restart php5-fpm

- name: php5-fpm - ini settings
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf section={{ item.value.chapter }} option={{ item.key }} value={{ item.value.val }}
  with_dict: '{{ php5_fpm_ini }}'
  notify:
  - restart php5-fpm

- name: php7.2 - add key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: php7.2 - add php7.2 source
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    state: present
    filename: php

- name: php7.2 - install packages
  apt: name={{ item }} state=latest
  with_items: '{{ php72_packages }}'

- name: php7.2 - ini settings
  ini_file: dest=/etc/php/7.2/fpm/php.ini section={{ item.value.chapter }} option={{ item.key }} value={{ item.value.val }}
  with_dict: '{{ php72_ini }}'
  notify:
  - restart php7.2-fpm

- name: php7.2-fpm - ini settings
  ini_file: dest=/etc/php/7.2/fpm/pool.d/www.conf section={{ item.value.chapter }} option={{ item.key }} value={{ item.value.val }}
  with_dict: '{{ php72_fpm_ini }}'
  notify:
  - restart php7.2-fpm
