---
apache2_packages:
  - apache2
  - apache2-utils

mailhog_dir: /opt/mailhog
mailhog_get_url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64

mc_config:
  vagrant:
    dir: /home/vagrant/.config/mc
    dir_perm: '0755'
    file_perm: '0644'
    file_prefix: mc_
    mc_1: ini
    mc_2: panels.ini
    skin: nicedark
  root:
    dir: /root/.config/mc
    dir_perm: '0700'
    file_perm: '0600'
    file_prefix: mc_
    mc_1: ini
    mc_2: panels.ini
    skin: gotar

mysql_ini:
  user:
    chapter: client
    val: root
  password:
    chapter: client
    val: root

mysql_packages:
  - mysql-client
  - mysql-common
  - mysql-server
  - python-mysqldb

mysql_root_pass: root

nodejs_modules:
  - bower
  - eslint
  - gulp-cli
  - vue-cli

php56_ini:
  sendmail_path:
    chapter: mail function
    val: '{{ mailhog_dir }}/mailhog sendmail'
  error_reporting:
    chapter: PHP
    val: E_ALL
  display_errors:
    chapter: PHP
    val: On
  display_startup_errors:
    chapter: PHP
    val: On
  max_execution_time:
    chapter: PHP
    val: 60
  memory_limit:
    chapter: PHP
    val: 256M
  post_max_size:
    chapter: PHP
    val: 50M
  short_open_tag:
    chapter: PHP
    val: On
  track_errors:
    chapter: PHP
    val: On
  upload_max_filesize:
    chapter: PHP
    val: 50M
  xdebug.collect_params:
    chapter: Xdebug
    val: 4
  xdebug.collect_includes:
    chapter: Xdebug
    val: 1
  xdebug.default_enable:
    chapter: Xdebug
    val: 1
  xdebug.dump.REQUEST:
    chapter: Xdebug
    val: '*'
  xdebug.dump.SESSION:
    chapter: Xdebug
    val: '*'
  xdebug.var_display_max_children:
    chapter: Xdebug
    val: -1
  xdebug.var_display_max_depth:
    chapter: Xdebug
    val: 5
  xdebug.idekey:
    chapter: Xdebug
    val: ECLIPSE
  xdebug.remote_enable:
    chapter: Xdebug
    val: 1
  xdebug.remote_host:
    chapter: Xdebug
    val: 10.0.2.2
  xdebug.remote_port:
    chapter: Xdebug
    val: 9001

php56_fpm_ini:
  listen:
    chapter: www
    val: '127.0.0.1:9056'
  group:
    chapter: www
    val: vagrant
  security.limit_extensions:
    chapter: www
    val: .php .html .htm
  user:
    chapter: www
    val: vagrant

php56_packages:
  - php5.6
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-fileinfo
  - php5.6-fpm
  - php5.6-gd
  - php5.6-iconv
  - php5.6-json
  - php5.6-mbstring
  - php5.6-mcrypt
  - php5.6-mysqli
  - php5.6-mysqlnd
  - php5.6-oauth
  - php5.6-opcache
  - php5.6-pdo
  - php5.6-pdo-mysql
  - php5.6-xdebug

php72_ini:
  sendmail_path:
    chapter: mail function
    val: '{{ mailhog_dir }}/mailhog sendmail'
  error_reporting:
    chapter: PHP
    val: E_ALL
  display_errors:
    chapter: PHP
    val: On
  display_startup_errors:
    chapter: PHP
    val: On
  max_execution_time:
    chapter: PHP
    val: 60
  memory_limit:
    chapter: PHP
    val: 256M
  post_max_size:
    chapter: PHP
    val: 50M
  track_errors:
    chapter: PHP
    val: On
  upload_max_filesize:
    chapter: PHP
    val: 50M
  xdebug.collect_params:
    chapter: Xdebug
    val: 4
  xdebug.collect_includes:
    chapter: Xdebug
    val: 1
  xdebug.default_enable:
    chapter: Xdebug
    val: 1
  xdebug.dump.REQUEST:
    chapter: Xdebug
    val: '*'
  xdebug.dump.SESSION:
    chapter: Xdebug
    val: '*'
  xdebug.var_display_max_children:
    chapter: Xdebug
    val: -1
  xdebug.var_display_max_depth:
    chapter: Xdebug
    val: 5
  xdebug.idekey:
    chapter: Xdebug
    val: ECLIPSE
  xdebug.remote_enable:
    chapter: Xdebug
    val: 1
  xdebug.remote_host:
    chapter: Xdebug
    val: 10.0.2.2
  xdebug.remote_port:
    chapter: Xdebug
    val: 9001

php72_fpm_ini:
  listen:
    chapter: www
    val: '127.0.0.1:9072'
  group:
    chapter: www
    val: vagrant
  security.limit_extensions:
    chapter: www
    val: .php .html .htm
  user:
    chapter: www
    val: vagrant

php72_packages:
  - php7.2
  - php7.2-cli
  - php7.2-common
  - php7.2-curl
  - php7.2-fileinfo
  - php7.2-fpm
  - php7.2-gd
  - php7.2-iconv
  - php7.2-json
  - php7.2-mbstring
  - php7.2-mysqli
  - php7.2-mysqlnd
  - php7.2-oauth
  - php7.2-opcache
  - php7.2-pdo
  - php7.2-pdo-mysql
  - php7.2-xdebug

phpmyadmin_debconf:
  q1:
    question: phpmyadmin/dbconfig-install
    vtype: boolean
    val: true
  q2:
    question: phpmyadmin/app-password-confirm
    vtype: password
    val: '{{ mysql_root_pass }}'
  q3:
    question: phpmyadmin/mysql/admin-pass
    vtype: password
    val: '{{ mysql_root_pass }}'
  q4:
    question: phpmyadmin/mysql/app-pass
    vtype: password
    val: '{{ mysql_root_pass }}'
  q5:
    question: phpmyadmin/reconfigure-webserver
    vtype: select
    val: apache2

sites_homedir: /vagrant/sites

sites:
  test:
    domain: test.loc
    root: '{{ sites_homedir }}/test'
    root_www: '{{ sites_homedir }}/test/www'

system_packages:
  - aptitude
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - git
  - libgd3
  - libgd-dev
  - libgd-tools
  - lsb-release
  - lynx
  - mc
  - vim

timezone: Europe/Moscow
