---
apache2_packages:
  - apache2
  - apache2-utils

mailhog_dir: /opt/mailhog
mailhog_get_url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64

mc_config:
  vagrant:
    dir: /home/vagrant/.config/mc
    dir_perm: '0755'
    file_perm: '0644'
    file_prefix: mc_
    mc_1: ini
    mc_2: panels.ini
    skin: nicedark
  root:
    dir: /root/.config/mc
    dir_perm: '0700'
    file_perm: '0600'
    file_prefix: mc_
    mc_1: ini
    mc_2: panels.ini
    skin: gotar

mysql_ini:
  user:
    chapter: client
    val: root
  password:
    chapter: client
    val: root

mysql_packages:
  - mysql-client
  - mysql-common
  - mysql-server
  - python-mysqldb

mysql_root_pass: root

nodejs_modules:
  - bower
  - eslint
  - gulp-cli
  - vue-cli

php56_ini:
  sendmail_path:
    chapter: mail function
    val: '{{ mailhog_dir }}/mailhog sendmail'
  error_reporting:
    chapter: PHP
    val: E_ALL
  display_errors:
    chapter: PHP
    val: On
  display_startup_errors:
    chapter: PHP
    val: On
  max_execution_time:
    chapter: PHP
    val: 60
  memory_limit:
    chapter: PHP
    val: 256M
  post_max_size:
    chapter: PHP
    val: 50M
  short_open_tag:
    chapter: PHP
    val: On
  track_errors:
    chapter: PHP
    val: On
  upload_max_filesize:
    chapter: PHP
    val: 50M
  xdebug.collect_params:
    chapter: Xdebug
    val: 4
  xdebug.collect_includes:
    chapter: Xdebug
    val: 1
  xdebug.default_enable:
    chapter: Xdebug
    val: 1
  xdebug.dump.REQUEST:
    chapter: Xdebug
    val: '*'
  xdebug.dump.SESSION:
    chapter: Xdebug
    val: '*'
  xdebug.var_display_max_children:
    chapter: Xdebug
    val: -1
  xdebug.var_display_max_depth:
    chapter: Xdebug
    val: 5
  xdebug.idekey:
    chapter: Xdebug
    val: ECLIPSE
  xdebug.remote_enable:
    chapter: Xdebug
    val: 1
  xdebug.remote_host:
    chapter: Xdebug
    val: 10.0.2.2
  xdebug.remote_port:
    chapter: Xdebug
    val: 9001

php5_fpm_ini:
  listen:
    chapter: www
    val: '127.0.0.1:9056'
  group:
    chapter: www
    val: vagrant
  security.limit_extensions:
    chapter: www
    val: .php .html .htm
  user:
    chapter: www
    val: vagrant

php56_packages:
  - php5
  - php5-common
  - php5-curl
  - php5-fpm
  - php5-gd
  - php5-json
  - php5-mcrypt
  - php5-mysqlnd
  - php5-oauth
  - php5-xdebug

php71_ini:
  sendmail_path:
    chapter: mail function
    val: '{{ mailhog_dir }}/mailhog sendmail'
  error_reporting:
    chapter: PHP
    val: E_ALL
  display_errors:
    chapter: PHP
    val: On
  display_startup_errors:
    chapter: PHP
    val: On
  max_execution_time:
    chapter: PHP
    val: 60
  memory_limit:
    chapter: PHP
    val: 256M
  post_max_size:
    chapter: PHP
    val: 50M
  track_errors:
    chapter: PHP
    val: On
  upload_max_filesize:
    chapter: PHP
    val: 50M
  xdebug.collect_params:
    chapter: Xdebug
    val: 4
  xdebug.collect_includes:
    chapter: Xdebug
    val: 1
  xdebug.default_enable:
    chapter: Xdebug
    val: 1
  xdebug.dump.REQUEST:
    chapter: Xdebug
    val: '*'
  xdebug.dump.SESSION:
    chapter: Xdebug
    val: '*'
  xdebug.var_display_max_children:
    chapter: Xdebug
    val: -1
  xdebug.var_display_max_depth:
    chapter: Xdebug
    val: 5
  xdebug.idekey:
    chapter: Xdebug
    val: ECLIPSE
  xdebug.remote_enable:
    chapter: Xdebug
    val: 1
  xdebug.remote_host:
    chapter: Xdebug
    val: 10.0.2.2
  xdebug.remote_port:
    chapter: Xdebug
    val: 9001

php71_fpm_ini:
  listen:
    chapter: www
    val: '127.0.0.1:9071'
  group:
    chapter: www
    val: vagrant
  security.limit_extensions:
    chapter: www
    val: .php .html .htm
  user:
    chapter: www
    val: vagrant

php71_packages:
  - php7.1
  - php7.1-cli
  - php7.1-common
  - php7.1-curl
  - php7.1-fileinfo
  - php7.1-fpm
  - php7.1-gd
  - php7.1-iconv
  - php7.1-json
  - php7.1-mbstring
  - php7.1-mcrypt
  - php7.1-mysqli
  - php7.1-mysqlnd
  - php7.1-oauth
  - php7.1-opcache
  - php7.1-pdo
  - php7.1-pdo-mysql
  - php7.1-xdebug

phpmyadmin_debconf:
  q1:
    question: phpmyadmin/dbconfig-install
    vtype: boolean
    val: true
  q2:
    question: phpmyadmin/app-password-confirm
    vtype: password
    val: '{{ mysql_root_pass }}'
  q3:
    question: phpmyadmin/mysql/admin-pass
    vtype: password
    val: '{{ mysql_root_pass }}'
  q4:
    question: phpmyadmin/mysql/app-pass
    vtype: password
    val: '{{ mysql_root_pass }}'
  q5:
    question: phpmyadmin/reconfigure-webserver
    vtype: select
    val: apache2

sites_homedir: /vagrant/sites

sites:
  test:
    domain: test.dev
    root: '{{ sites_homedir }}/test.dev'
    root_www: '{{ sites_homedir }}/test.dev/www'

system_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - git
  - libgd3
  - libgd-dev
  - libgd-tools
  - lsb-release
  - lynx
  - mc
  - vim

timezone: Europe/Moscow
