---
- name: restart apache2
  service: name=apache2 state=restarted

- name: restart mysql
  service: name=mysql state=restarted

- name: restart php5-fpm
  service: name=php5-fpm state=restarted

- name: restart php7.1-fpm
  service: name=php7.1-fpm state=restarted